path: config/features
name: data_features.yaml
nb_runs: 50
dataset:
  path: amex_data
  train: train.csv
  test: test.csv
target: target
drop_features:
- customer_ID
- S_2
cat_features:
- B_30
- B_38
- D_114
- D_116
- D_117
- D_120
- D_126
- D_63
- D_64
- D_66
- D_68