data:
  raw_data_path: "data/default_of_credit_card_clients.csv"
  processed_data_path: "data/processed_data"
  inference_data_path: "data/inference_data.csv"
  test_data_path: "data/processed_data"
  predict_data_path: "data/predict_data.csv"
  target_column: "default payment next month"
model:
  name: "default_of_credit_card_clients"
  version: "0.0.1"
  type: "gbm"  # Can be 'nn' for Neural Network or 'gbm' for Gradient Boosting Machine
  model_path: "models/${name}_${version}.pkl"
  predictions_path: "models/predictions.csv"
  hidden_layers: [64, 32, 16]

training:
  epochs: 32
  batch_size: 64
  learning_rate: 0.001

features:
  numerical:
    - "LIMIT_BAL"
    - "AGE"
    - "BILL_AMT1"
    - "BILL_AMT2"
    - "BILL_AMT3"
    - "BILL_AMT4"
    - "BILL_AMT5"
    - "BILL_AMT6"
    - "PAY_AMT1"
    - "PAY_AMT2"
    - "PAY_AMT3"
    - "PAY_AMT4"
    - "PAY_AMT5"
    - "PAY_AMT6"
  categorical:
    - "SEX"
    - "EDUCATION"
    - "MARRIAGE"
    - "PAY_0"
    - "PAY_2"
    - "PAY_3"
    - "PAY_4"
    - "PAY_5"
    - "PAY_6"